services:
  react_quest:
    build:
      context: ./docker/react
    container_name: react_quest
    tty: true
    ports:
      - 5173:5173
    volumes:
      - ./proj:/home/react-ts-app
    command: npm run dev -- --host
